# Generated by Django 2.2.3 on 2019-07-09 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_vip_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='vip_id',
            field=models.IntegerField(default=1),
        ),
    ]
